language: go
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - liblz4-dev
before_script:
  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/tools/cmd/vet
script: go vet ./... && go test -race -bench=. -cover ./...
