language: go
go:
  - 1.3
before_install:
 - sudo add-apt-repository ppa:nathan-renniewaldock/ppa -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq liblz4-dev
script: go test -bench=. -v github.com/cyberdelia/lz4
